object Endpoint "i2m1" {
}

object Endpoint "i2m2" {
  host = "i2m2"
}

object Zone "master" {
	endpoints = [ "i2m1", "i2m2" ]
}

object Endpoint "i2s1" {
}

object Endpoint "i2s2" {
}

object Zone "satellite" {
	endpoints = [ "i2s1", "i2s2" ]
	parent = "master"
}

object Zone "global-templates" {
	global = true
}

object Zone "director-global" {
	global = true
}
