services:
  i2m1:
    image: icinga/icinga2
    hostname: &hostname i2m1
    container_name: *hostname
    environment:
      ICINGA_MASTER: 1
    volumes:
      - ./setup.sh:/setup.sh
    depends_on:
      - i2m1-icingadb
