/*
 * Host definitions with object attributes
 * used for apply rules for Service, Notification,
 * Dependency and ScheduledDowntime objects.
 *
 * Tip: Use `icinga2 object list --type Host` to
 * list all host objects after running
 * configuration validation (`icinga2 daemon -C`).
 */

/*
 * This is an example host based on your
 * local host's FQDN. Specify the NodeName
 * constant in `constants.conf` or use your
 * own description, e.g. "db-host-1".
 */

object Host "i2m1" {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"
  vars.icinga = "satellite"
  vars.partner = "i2m2"

  command_endpoint = name

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "i2m1"

  /* Set custom variable `os` for hostgroup assignment in `groups.conf`. */
  vars.os = "Linux"

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
}

object Host "i2m2" {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"
  vars.icinga = "satellite"
  vars.partner = "i2m1"

  command_endpoint = name

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "i2m2"

  /* Set custom variable `os` for hostgroup assignment in `groups.conf`. */
  vars.os = "Linux"

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
}


object Host "i2s1" {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"
  vars.icinga = "master"
  vars.partner = "i2s2"
  command_endpoint = name

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "i2s1"

  /* Set custom variable `os` for hostgroup assignment in `groups.conf`. */
  vars.os = "Linux"

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
}


object Host "i2s2" {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"
  vars.icinga = "master"
  vars.partner = "i2s1"

  command_endpoint = name

  /* Specify the address attributes for checks e.g. `ssh` or `http`. */
  address = "i2s2"

  /* Set custom variable `os` for hostgroup assignment in `groups.conf`. */
  vars.os = "Linux"

  /* Define notification mail attributes for notification apply rules in `notifications.conf`. */
  vars.notification["mail"] = {
    /* The UserGroup `icingaadmins` is defined in `users.conf`. */
    groups = [ "icingaadmins" ]
  }
}
