
template Host "nrpe-host" {
  max_check_attempts = 3
  retry_interval = 1m
  check_interval = 5m
  check_command = "hostalive"
  vars.os = "alpine"
  vars.nrpe = 1
}

object Host "nrz1" {
  address = name
  import "nrpe-host"
  check_command = "hostalive"
}

object Host "nrz2" {
  address = name
  import "nrpe-host"
  check_command = "hostalive"
}

apply Service "check_users" {
  display_name = "users"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_users"

  assign where host.vars.nrpe
}

apply Service "check_load" {
  display_name = "load"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_load"

  assign where host.vars.nrpe
}

apply Service "check_vda1" {
  display_name = "vda1"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_vda1"

  ignore where host.vars.os == "alpine"
  assign where host.vars.nrpe 
}

apply Service "check_zombie_procs" {
  display_name = "zombie"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_zombie_procs"

  assign where host.vars.nrpe
}

apply Service "check_total_procs" {
  display_name = "procs"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_total_procs"

  assign where host.vars.nrpe
}

apply Service "local-ping4" {
  display_name = "ping4"
  notes = "Ping Check from Icinga2 Satellite"
  #import "gold-service"
  check_command = "ping4"
  vars.ping_wrta = 200
  vars.ping_crta = 300
  //check is executed on the satellite node
  assign where host.address && host.zone == "satellite"
  //ignore where host.vars.nrpe
}
