


object Host "nrz1" {
  display_name = "NRPE 01"
  import "nrpe-host"

  address = name
}

object Host "nrz2" {
  display_name = "NRPE 02"
  import "nrpe-host"

  address = name
}

# -----





apply Service "check_vda1" {
  display_name = "vda1"
  notes = "NRPE Based Service"

  check_command = "nrpe"
  vars.nrpe_command = "check_vda1"

  ignore where host.vars.os == "alpine"
  assign where host.vars.nrpe 
}






