/*
 * These are generic `ping4` and `ping6`
 * checks applied to all hosts having the
 * `address` resp. `address6` attribute
 * defined.
 */
apply Service "ping4" {
  check_command = "ping4"

  assign where host.vars.icinga
  assign where host.vars.nrpe
}

apply Service "ping6" {
  import "generic-service"

  check_command = "ping6"

  assign where host.address6
}


apply Service "load" {

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_load"
    notes = "NRPE: Load thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "load"
    command_endpoint = host.name
    notes = "Icinga2: Load thresholds can be set using custom variables."
  }

  assign where host.vars.icinga
  assign where host.vars.nrpe
}


apply Service "procs" {

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_total_procs"
    notes = "NRPE: Process thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "procs"
    command_endpoint = host.name
    notes = "Icinga2: Processes thresholds can be set using custom variables."
  }

  assign where host.vars.icinga
  assign where host.vars.nrpe
}


apply Service "zombie" {

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_zombie_procs"
    notes = "NRPE: Zombie process thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "procs"
    vars.procs_state = "Z"
    vars.procs_warning = 5
    vars.procs_critical = 10
    command_endpoint = host.name
    notes = "Icinga2: Zombie process thresholds can be set using custom variables."
  }

  assign where host.vars.icinga
  assign where host.vars.nrpe
}


apply Service "users" {

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_users"
    notes = "NRPE: User thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "users"
    command_endpoint = host.name
    notes = "Icinga2: User thresholds can be set using custom variables."
  }

  assign where host.vars.icinga
  assign where host.vars.nrpe
}


apply Service "swap" {
  import "platinum-service"

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_swap"
    notes = "NRPE: Swap space thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "swap"
    command_endpoint = host.name
    notes = "Icinga2: Swap space thresholds can be set using custom variables."
  }

  assign where host.vars.icinga
  assign where host.vars.nrpe
}
