/*
 * These are generic `ping4` and `ping6`
 * checks applied to all hosts having the
 * `address` resp. `address6` attribute
 * defined.
 */
apply Service "ping4" {
  check_command = "ping4"

  assign where host.address
}

apply Service "ping6" {
  import "generic-service"

  check_command = "ping6"

  assign where host.address6
}


apply Service "load" {

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_load"
    notes = "NRPE: Load thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "load"
    command_endpoint = host.name
    notes = "Icinga2: Load thresholds can be set using custom variables."
  }

  assign where host.address
}


apply Service "procs" {
  import "platinum-service"

  if (host.vars.nrpe) {
    check_command = "nrpe"
    vars.nrpe_command = "check_total_procs"
    notes = "NRPE: Process thresholds are defined by nrpe.cfg on the target host."
  } else {
    check_command = "procs"
    command_endpoint = host.name
    notes = "Icinga2: Processes thresholds can be set using custom variables."
  }

  assign where host.address
}