template Service "platinum-service" {
  max_check_attempts = 2
  check_interval = 60s
  retry_interval = 15s
}

template Service "gold-service" {
  max_check_attempts = 2
  check_interval = 180s
  retry_interval = 45s
}

/*
template Service "default-service" {
  max_check_attempts = 3
  check_interval = 5m
  retry_interval = 1m
}
*/

template Service "silver-service" {
  max_check_attempts = 3
  check_interval = 15m
  retry_interval = 5m
}

template Service "bronze-service" {
  max_check_attempts = 4
  check_interval = 1h
  retry_interval = 15m
}

/**
 * Provides default settings for services. By convention
 * all services should import this template.
 */
template Service "generic-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
}

template Host "nrpe-host" {
  check_command = "hostalive"

  vars.os = "alpine"
  vars.nrpe = 1
}